"""add parsed_data to resumes

Revision ID: b4382f4ef6ab
Revises: 5bfd9d7295ff
Create Date: 2026-07-24 02:23:25.364377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4382f4ef6ab'
down_revision: Union[str, Sequence[str], None] = '5bfd9d7295ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('parsed_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'parsed_data')
    # ### end Alembic commands ###
